# use the latest ubuntu environment (18.04) available on travis
dist: bionic

language: go

go:
  - 1.14.x

script:
  - make

# Don't email me the results of the test runs.
notifications:
  email: false
